repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local
    hooks:
      - id: ruff
        name: ruff (workspace venv)
        entry: ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff-format (workspace venv)
        entry: ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
